# coding: utf-8

# flake8: noqa

"""
    CoinGecko API V3

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from coingecko_py.swagger_generated.swagger_client.api.coingecko_api import CoingeckoApi

# import ApiClient
from coingecko_py.swagger_generated.swagger_client.api_client import ApiClient
from coingecko_py.swagger_generated.swagger_client.configuration import Configuration

# import models into sdk package
