# coding: utf-8

"""
    CoinGecko API V3

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 3.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.coingecko_api import CoingeckoApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCoingeckoApi(unittest.TestCase):
    """CoingeckoApi unit test stubs"""

    def setUp(self):
        self.api = CoingeckoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_asset_platforms_get(self):
        """Test case for asset_platforms_get

        List all asset platforms (Blockchain networks)  # noqa: E501
        """
        pass

    def test_coins_categories_get(self):
        """Test case for coins_categories_get

        List all categories with market data  # noqa: E501
        """
        pass

    def test_coins_categories_list_get(self):
        """Test case for coins_categories_list_get

        List all categories  # noqa: E501
        """
        pass

    def test_coins_id_contract_contract_address_get(self):
        """Test case for coins_id_contract_contract_address_get

        Get coin info from contract address  # noqa: E501
        """
        pass

    def test_coins_id_contract_contract_address_market_chart_get(self):
        """Test case for coins_id_contract_contract_address_market_chart_get

        Get historical market data include price, market cap, and 24h volume (granularity auto) from a contract address   # noqa: E501
        """
        pass

    def test_coins_id_contract_contract_address_market_chart_range_get(self):
        """Test case for coins_id_contract_contract_address_market_chart_range_get

        Get historical market data include price, market cap, and 24h volume within a range of timestamp (granularity auto) from a contract address  # noqa: E501
        """
        pass

    def test_coins_id_get(self):
        """Test case for coins_id_get

        Get current data (name, price, market, ... including exchange tickers) for a coin  # noqa: E501
        """
        pass

    def test_coins_id_history_get(self):
        """Test case for coins_id_history_get

        Get historical data (name, price, market, stats) at a given date for a coin  # noqa: E501
        """
        pass

    def test_coins_id_market_chart_get(self):
        """Test case for coins_id_market_chart_get

        Get historical market data include price, market cap, and 24h volume (granularity auto)  # noqa: E501
        """
        pass

    def test_coins_id_market_chart_range_get(self):
        """Test case for coins_id_market_chart_range_get

        Get historical market data include price, market cap, and 24h volume within a range of timestamp (granularity auto)  # noqa: E501
        """
        pass

    def test_coins_id_ohlc_get(self):
        """Test case for coins_id_ohlc_get

        Get coin's OHLC  # noqa: E501
        """
        pass

    def test_coins_id_status_updates_get(self):
        """Test case for coins_id_status_updates_get

        Get status updates for a given coin  # noqa: E501
        """
        pass

    def test_coins_id_tickers_get(self):
        """Test case for coins_id_tickers_get

        Get coin tickers (paginated to 100 items)  # noqa: E501
        """
        pass

    def test_coins_list_get(self):
        """Test case for coins_list_get

        List all supported coins id, name and symbol (no pagination required)  # noqa: E501
        """
        pass

    def test_coins_markets_get(self):
        """Test case for coins_markets_get

        List all supported coins price, market cap, volume, and market related data  # noqa: E501
        """
        pass

    def test_companies_public_treasury_coin_id_get(self):
        """Test case for companies_public_treasury_coin_id_get

        Get public companies data  # noqa: E501
        """
        pass

    def test_derivatives_exchanges_get(self):
        """Test case for derivatives_exchanges_get

        List all derivative exchanges  # noqa: E501
        """
        pass

    def test_derivatives_exchanges_id_get(self):
        """Test case for derivatives_exchanges_id_get

        show derivative exchange data  # noqa: E501
        """
        pass

    def test_derivatives_exchanges_list_get(self):
        """Test case for derivatives_exchanges_list_get

        List all derivative exchanges name and identifier  # noqa: E501
        """
        pass

    def test_derivatives_get(self):
        """Test case for derivatives_get

        List all derivative tickers  # noqa: E501
        """
        pass

    def test_exchange_rates_get(self):
        """Test case for exchange_rates_get

        Get BTC-to-Currency exchange rates  # noqa: E501
        """
        pass

    def test_exchanges_get(self):
        """Test case for exchanges_get

        List all exchanges  # noqa: E501
        """
        pass

    def test_exchanges_id_get(self):
        """Test case for exchanges_id_get

        Get exchange volume in BTC and top 100 tickers only  # noqa: E501
        """
        pass

    def test_exchanges_id_status_updates_get(self):
        """Test case for exchanges_id_status_updates_get

        Get status updates for a given exchange  # noqa: E501
        """
        pass

    def test_exchanges_id_tickers_get(self):
        """Test case for exchanges_id_tickers_get

        Get exchange tickers (paginated, 100 tickers per page)  # noqa: E501
        """
        pass

    def test_exchanges_id_volume_chart_get(self):
        """Test case for exchanges_id_volume_chart_get

        Get volume_chart data for a given exchange  # noqa: E501
        """
        pass

    def test_exchanges_list_get(self):
        """Test case for exchanges_list_get

        List all supported markets id and name (no pagination required)  # noqa: E501
        """
        pass

    def test_finance_platforms_get(self):
        """Test case for finance_platforms_get

        List all finance platforms  # noqa: E501
        """
        pass

    def test_finance_products_get(self):
        """Test case for finance_products_get

        List all finance products  # noqa: E501
        """
        pass

    def test_global_decentralized_finance_defi_get(self):
        """Test case for global_decentralized_finance_defi_get

        Get cryptocurrency global decentralized finance(defi) data  # noqa: E501
        """
        pass

    def test_global_get(self):
        """Test case for global_get

        Get cryptocurrency global data  # noqa: E501
        """
        pass

    def test_indexes_get(self):
        """Test case for indexes_get

        List all market indexes  # noqa: E501
        """
        pass

    def test_indexes_list_get(self):
        """Test case for indexes_list_get

        list market indexes id and name  # noqa: E501
        """
        pass

    def test_indexes_market_id_id_get(self):
        """Test case for indexes_market_id_id_get

        get market index by market id and index id  # noqa: E501
        """
        pass

    def test_ping_get(self):
        """Test case for ping_get

        Check API server status  # noqa: E501
        """
        pass

    def test_search_get(self):
        """Test case for search_get

        Search for coins, categories and markets on CoinGecko  # noqa: E501
        """
        pass

    def test_search_trending_get(self):
        """Test case for search_trending_get

        Get trending search coins (Top-7) on CoinGecko in the last 24 hours  # noqa: E501
        """
        pass

    def test_simple_price_get(self):
        """Test case for simple_price_get

        Get the current price of any cryptocurrencies in any other supported currencies that you need.  # noqa: E501
        """
        pass

    def test_simple_supported_vs_currencies_get(self):
        """Test case for simple_supported_vs_currencies_get

        Get list of supported_vs_currencies.  # noqa: E501
        """
        pass

    def test_simple_token_price_id_get(self):
        """Test case for simple_token_price_id_get

        Get current price of tokens (using contract addresses) for a given platform in any other currency that you need.  # noqa: E501
        """
        pass

    def test_status_updates_get(self):
        """Test case for status_updates_get

        List all status_updates with data (description, category, created_at, user, user_title and pin)  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
